---
- hosts: workstation

  tasks:
    - name: install Keepassx
      mac_pkg: pkg_type=app
               url=https://www.keepassx.org/releases/2.0.2/KeePassX-2.0.2.dmg
               archive_type=dmg archive_path=KeePassX.app
      sudo: yes
