---
- hosts: workstation

  tasks:
    - name: install virtualbox
      mac_pkg: pkg_name=org.virtualbox.pkg.virtualbox pkg_version=5.1.2
               url=http://download.virtualbox.org/virtualbox/5.1.2/VirtualBox-5.1.2-108956-OSX.dmg
               archive_type=dmg archive_path=VirtualBox.pkg
      sudo: yes

